// Per-vertical content shared between MarketingHome (small cards
// linking to /for/:slug) and VerticalPage (the full page itself).
// Pure data - no React imports - so MarketingHome can pull this
// without dragging the VerticalPage component into the index chunk.
//
// Adding a vertical: drop a row here, link from anywhere; everything
// else (route, SEO meta, cross-links) is already wired.
export const VERTICALS = {
  'massage-therapists': {
    icon: 'Spark',
    angle: 'massage therapists',
    homeLine: 'Intake forms auto-send before sessions. Reminders cut no-shows.',
    headline: 'Bookings, intake forms, and reminders in one place.',
    sub: "One workspace for booking, intake forms, payments, and the client portal - instead of stitching together three or four separate tools.",
    bullets: [
      { title: 'Auto-send intake forms', body: 'Attach a SOAP-note intake form to each service. Ivy sends it the moment a client books - no more "did you fill out the form?" texts.' },
      { title: 'No-show reduction', body: 'Email + SMS reminders ship 24h and 2h before the session. Clients can confirm or reschedule from the link without calling.' },
      { title: 'Built-in deposits', body: 'Charge a deposit on booking via your own Stripe. Walk-outs become non-issues.' },
      { title: 'Client portal', body: 'Past sessions, signed waivers, invoices, package balances - all in their pocket. Free for clients, forever.' },
    ],
    use: "Add your sessions (60-min massage, 90-min, deep-tissue), set Mon-Fri 9-5 availability, share /book/your-name, and you're live.",
  },
  'hair-stylists': {
    icon: 'Gift',
    angle: 'hair stylists & barbers',
    homeLine: 'Deposits on booking, packages for repeat clients, rebooking nudges.',
    headline: 'Booking, deposits, packages, and rebooking - all native.',
    sub: "We don't take a cut of your sales - Stripe's standard processing fee is the only fee, and it goes straight to your account. One subscription covers booking, payments, and the client CRM.",
    bullets: [
      { title: 'Deposits on every booking', body: "Set a deposit per service. Stripe collects on confirm; the rest at the chair." },
      { title: 'Service packages', body: '5-pack of cut-and-color, 10-pack of trims. Sell the bundle; Ivy consumes a credit per booking automatically.' },
      { title: 'Rebooking nudges', body: "Ivy spots clients who haven't rebooked since their last cut and drafts a check-in you can send in one tap." },
      { title: 'Reviews where it matters', body: 'Auto-prompt for a review after the appointment. Highlights show up on your /book/your-name page.' },
    ],
    use: 'Add cut, color, mani, etc. with prices. Set deposits where it matters. Tag returning clients as "active" and Ivy quietly tracks their cadence.',
  },
  'personal-trainers': {
    icon: 'Trending',
    angle: 'personal trainers & fitness coaches',
    homeLine: 'Group classes with capacity, recurring sessions, payment-on-booking.',
    headline: 'Group classes, recurring sessions, and packages - without enterprise-grade overhead.',
    sub: 'Schedule 1-on-1s and group classes. Sell session packs. Collect on booking. Let your AI coach (Ivy) help you spot at-risk clients before they ghost.',
    bullets: [
      { title: 'Group classes with capacity', body: 'Set a service to "capacity 12". Clients book individual seats; the slot fills up like a real class roster.' },
      { title: 'Recurring sessions', body: 'Tuesday + Thursday 6 AM, every week, until canceled. Ivy creates the booking series and reminders fire for each.' },
      { title: 'Session packs', body: '10-pack of training, $850. Ivy bills upfront and consumes one credit per session - refunds the credit if you cancel.' },
      { title: 'Quiet-client alerts', body: "Ivy lists who hasn't booked in 3+ weeks and drafts personalized check-ins. Two-tap to send." },
    ],
    use: 'Set up your services (1-on-1, group HIIT, nutrition consult) with capacities, build packages, share the booking link, and Ivy starts watching.',
  },
  'coaches': {
    icon: 'Doc',
    angle: 'coaches & consultants',
    homeLine: 'Discovery calls, retainers, signed agreements - same thread.',
    headline: 'Discovery calls, retainers, signed agreements - same thread.',
    sub: "One link replaces a stack of separate scheduling, contracting, and e-signing tools. Drop your booking link, attach the agreement to the engagement service, get e-signed automatically.",
    bullets: [
      { title: 'E-signing built in', body: 'Build your own agreement template once. Attach it to your "Strategy engagement" service. Ivy sends it the moment they book and tracks signatures.' },
      { title: 'Retainer invoices', body: "Recurring monthly invoices via Stripe. Auto-payment if their card's on file; reminders if not." },
      { title: 'Discovery → engagement', body: '15-min discovery → if they convert, the agreement, deposit invoice, and follow-up cadence all chain off the same client record.' },
      { title: 'Ivy as your prep assistant', body: 'Ask "Pull up everything on Sarah before our 3pm call" - Ivy summarizes their notes, last session, and open work.' },
    ],
    use: 'Service: "Discovery call (free)" + "Strategy engagement ($X)". Attach your agreement to the second. Drop the booking link in your bio.',
  },
  'cleaners': {
    icon: 'Check',
    angle: 'cleaners & home-service pros',
    homeLine: 'Recurring jobs, upfront deposits, automatic invoices on completion.',
    headline: 'Recurring jobs, upfront deposits, automatic invoices.',
    sub: 'Field service software is overkill. Spreadsheets are underkill. Ivy sits in between - one place for recurring bookings, deposits, post-job invoices, and follow-up.',
    bullets: [
      { title: 'Recurring jobs', body: '"Every other Tuesday at 10" - set the recurrence once, Ivy creates each booking and reminders fire automatically.' },
      { title: 'Deposit on booking', body: 'Charge 50% on confirm via Stripe; balance after the job. Cancellations under 24h forfeit the deposit if you set it that way.' },
      { title: 'Invoice on completion', body: 'Mark the booking complete → Ivy drafts the invoice with your standard line items. Edit, send, paid in 2 minutes.' },
      { title: 'Client portal for repeat work', body: 'Long-time clients book recurring jobs themselves through their portal. No more "can you come Thursday?" texts.' },
    ],
    use: 'Add services (deep clean, weekly clean, move-out), set deposit %, build a recurring service for your standing customers, share the link.',
  },
  'photographers': {
    icon: 'Image', angle: 'photographers',
    homeLine: 'Galleries, contracts, deposits - without the SaaS sprawl.',
    headline: 'Galleries, contracts, deposits - one workspace.',
    sub: "Replace your shoot-day toolchain. Ivy handles inquiry → contract → deposit → shoot → gallery delivery → final invoice, all in one place.",
    bullets: [
      { title: 'Multi-signer contracts', body: 'Send the contract from a template; client e-signs, you countersign. Stored beside their booking forever.' },
      { title: 'Deposit + balance flow', body: '50% on contract, balance after delivery. Stripe handles both; Ivy chases the balance automatically.' },
      { title: 'Branded gallery page', body: 'Build a gallery page on your own custom domain that mirrors your brand - clients see your name, not ours.' },
      { title: 'Lead capture from your site', body: 'Embed an inquiry form on any site; new leads land in your CRM with their wedding date already populated.' },
    ],
    use: 'Add packages (engagement, half-day, full-day), upload your standard contract, share your booking link.',
  },
  'videographers': {
    icon: 'Image', angle: 'videographers',
    homeLine: 'Contracts, deliverables, project timelines - without 4 tools.',
    headline: 'From inquiry to final cut, one workspace.',
    sub: 'Manage shoots, contracts, deposits, and revisions inside Ivy. Clients see one branded portal - not five email threads.',
    bullets: [
      { title: 'Project tracking', body: 'Group each shoot’s bookings, invoices, and files under one project and move it through your stages.' },
      { title: 'Deliver in the portal', body: 'Share the final cut through the client’s portal once their invoice is paid.' },
      { title: 'Recurring retainers', body: 'Bill monthly content packages on a recurring invoice - set it once and it sends every cycle.' },
      { title: 'Tax-ready expenses', body: 'Track equipment, mileage, contractor fees - exports straight into your tax software.' },
    ],
    use: 'Add your packages, build a project template for each shoot type, share the inquiry link on your site.',
  },
  'makeup-artists': {
    icon: 'Spark', angle: 'makeup artists',
    homeLine: 'On-location bookings, trial deposits, wedding-day flow.',
    headline: 'Trials, weddings, and editorial - all in one calendar.',
    sub: 'Track multi-stop wedding days, trial appointments, and event team members in one workspace built for solo MUAs.',
    bullets: [
      { title: 'Travel-time aware calendar', body: 'Add travel buffers between bookings so back-to-back shoots stay realistic.' },
      { title: 'Trial-to-wedding flow', body: 'A trial booking automatically prompts the wedding-day booking - never lose the rebook.' },
      { title: 'Deposit + tip flow', body: 'Deposit at booking; tip prompt in the post-event invoice. Stripe handles both.' },
      { title: 'Inspiration uploads', body: "Clients upload reference images to their booking. You see them when prepping - no more buried email attachments." },
    ],
    use: 'Add trial and wedding-day services, set travel buffer, share /book/your-name.',
  },
  'nail-techs': {
    icon: 'Heart', angle: 'nail techs',
    homeLine: 'Rebooking nudges, packages, no-show deposits.',
    headline: 'Built for the rebooking habit.',
    sub: 'Half your clients should be on a 4-week rotation. Ivy keeps them on track without you doing the work.',
    bullets: [
      { title: 'Smart rebook reminders', body: 'Set rotation (3wk, 4wk, 6wk); Ivy nudges clients before their slot lapses.' },
      { title: 'Service packages', body: '5-pack of fills, 10-pack of full sets. Clients buy ahead; Ivy consumes a credit per booking.' },
      { title: 'Deposit-or-card-on-file', body: 'Either charge a small deposit on booking, or save card-on-file to auto-charge no-shows.' },
      { title: 'Memberships', body: 'Monthly nails plan for $X. Auto-renew, auto-book, no-thinking-required.' },
    ],
    use: 'Add services with durations, set rotation cycles, turn on rebook nudges.',
  },
  'lash-artists': {
    icon: 'Spark', angle: 'lash artists',
    homeLine: 'Fill cadence, intake forms, before-and-afters.',
    headline: 'Fills, refills, and full sets - auto-tracked.',
    sub: 'Allergy intake forms, before-and-after photos, and fill cadence all live with the client record - no separate apps.',
    bullets: [
      { title: 'Per-service intake', body: "Allergy + style intake auto-sends on first booking; doesn't re-prompt on fills." },
      { title: 'Before/after gallery', body: "Upload to the client's record; surfaces on review prompts when you ask for testimonials." },
      { title: 'Fill cadence tracking', body: '2-week vs 3-week clients show in different reminder buckets automatically.' },
      { title: 'Card on file', body: 'Auto-charge for late cancellations per your policy - no awkward Venmo asks.' },
    ],
    use: 'Add full set, fill, and removal services. Upload intake template. Tag clients by cadence.',
  },
  'estheticians': {
    icon: 'Heart', angle: 'estheticians',
    homeLine: 'Service packages, treatment notes, recurring facials.',
    headline: 'Treatment plans + service memberships, one place.',
    sub: 'Track skin notes per client, sell facial-of-the-month memberships, and surface upcoming sessions in the client portal.',
    bullets: [
      { title: 'Per-client treatment notes', body: 'Private notes per client survive across every booking. Auto-suggested when you open their appointment.' },
      { title: 'Membership tiers', body: 'Monthly facial + add-ons. Auto-charge, auto-book the next slot.' },
      { title: 'Retail on invoices', body: 'Add retail products as invoice line items and sell them right alongside services.' },
      { title: 'Photo consent', body: 'Built-in consent form for before/after images. Client e-signs; you can use the photos.' },
    ],
    use: 'Add facials + add-ons, build a monthly membership, store your intake form.',
  },
  'yoga-instructors': {
    icon: 'Heart', angle: 'yoga instructors',
    homeLine: 'Class capacity, drop-ins vs members, waivers.',
    headline: 'Class scheduling + memberships, without Mindbody bloat.',
    sub: 'Run drop-in classes, sell class packs, manage members - all in one calendar with cleaner pricing than legacy fitness software.',
    bullets: [
      { title: 'Class capacity', body: 'Set max per class. Waitlist fills automatically when a spot opens.' },
      { title: 'Drop-in + pack pricing', body: 'Single drop-in, 5-pack, 10-pack, unlimited monthly - all per-class.' },
      { title: 'Liability waiver flow', body: 'First-time bookers must e-sign your waiver before the calendar confirms.' },
      { title: 'Member-only classes', body: 'Some classes only show in the member portal - drop-ins see the public schedule.' },
    ],
    use: 'Add your class types, set capacity, build a monthly unlimited tier, share your booking link.',
  },
  'pilates-teachers': {
    icon: 'Heart', angle: 'pilates teachers',
    homeLine: 'Equipment slots, private + duet sessions, monthly memberships.',
    headline: 'Reformer, mat, and duet - all on one schedule.',
    sub: 'Set class capacity to your equipment, price private vs duet sessions, and run monthly memberships - without legacy fitness CRM cost.',
    bullets: [
      { title: 'Capacity per class', body: 'Two reformers? Set the class capacity to two so a slot books up to your equipment, not past it.' },
      { title: 'Private + duet services', body: 'Offer private and duet sessions as separate services, each at its own price.' },
      { title: 'Monthly member tier', body: 'Sell a monthly membership that auto-charges; book the standing weekly slot as a recurring series.' },
      { title: 'Prepaid credits', body: 'Sell session packs with an expiry window; each booking draws a credit, and cancellations free it to rebook.' },
    ],
    use: 'Add private + duet + class services, set equipment capacity, build a monthly tier.',
  },
  'tattoo-artists': {
    icon: 'Edit', angle: 'tattoo artists',
    homeLine: 'Consults → deposits → sessions, all attached to one record.',
    headline: 'From consult to final session, one continuous record.',
    sub: "A tattoo project takes weeks. Ivy keeps the consult, deposit, design files, and every session on one client record - no more searching DMs.",
    bullets: [
      { title: 'Project-based bookings', body: 'Group all sessions for one tattoo under a single project so the client and you see the full arc.' },
      { title: 'Reference uploads', body: 'Client uploads inspo to their booking; you see everything when you start the design.' },
      { title: 'Deposit + per-session balance', body: 'Up-front deposit on consult, balance per session - Stripe handles both.' },
      { title: 'Aftercare follow-up', body: 'Auto-message at 1 week + 1 month for healing check-ins and rebook prompts.' },
    ],
    use: 'Add consult, design, and per-hour session services. Build a project template.',
  },
  'chiropractors': {
    icon: 'Heart', angle: 'chiropractors',
    homeLine: 'New-patient intake, care plans, insurance-ready receipts.',
    headline: 'Run care plans and cash-pay billing in one place.',
    sub: 'New-patient intake forms, multi-session care plans, and itemized insurance-ready receipts for cash-pay practices.',
    bullets: [
      { title: 'New-patient intake', body: "Allergies, history, current pain - all collected before they walk in." },
      { title: 'Care plans', body: 'Sell a 12-session adjustment plan up front; Ivy consumes a session per visit.' },
      { title: 'Insurance-ready receipts', body: 'Send itemized, branded invoices and receipts your cash-pay patients can submit to their insurer.' },
      { title: 'Recall reminders', body: '6-month wellness check-in nudges go out automatically.' },
    ],
    use: 'Add session types, build a care-plan package, upload your intake form.',
  },
  'physical-therapists': {
    icon: 'Heart', angle: 'physical therapists',
    homeLine: 'Progress notes, treatment plans, recurring care.',
    headline: 'Cash-pay PT, fully streamlined.',
    sub: 'For solo PTs running cash-pay practices: intake, progress notes, treatment plans, and insurance-ready receipts - all in one workspace.',
    bullets: [
      { title: 'Per-session progress notes', body: 'Quick-template notes that survive forever on the patient record.' },
      { title: 'HEP attachments', body: "Send the home exercise program PDF or video as part of the booking confirmation." },
      { title: 'Automated check-ins', body: 'Workflows send follow-up messages between sessions; log each visit’s notes on the client record.' },
      { title: 'Insurance-ready receipts', body: 'Itemized, branded invoices and receipts patients can submit for reimbursement.' },
    ],
    use: 'Add session types, build progress-note templates, set your invoice + receipt format.',
  },
  'doulas': {
    icon: 'Heart', angle: 'doulas & birth coaches',
    homeLine: 'Prenatal package, birth on-call, postpartum visits - one plan.',
    headline: 'From prenatal to postpartum, on one plan.',
    sub: 'Sell birth-support packages, schedule prenatals, log on-call hours, run postpartum follow-ups - all in one client record.',
    bullets: [
      { title: 'Birth package bundle', body: 'Three prenatals + birth-on-call + two postpartums. One price; Ivy tracks what\'s used.' },
      { title: 'On-call blocks', body: 'Block out on-call date ranges on your calendar so new bookings respect them.' },
      { title: 'Everything on one record', body: 'Keep every client’s key info, documents, and history on one record you can reference fast.' },
      { title: 'Postpartum follow-up', body: 'Auto-schedule the postpartum visits within X weeks of due date.' },
    ],
    use: 'Build the birth-support package, set service types, share with your local OB referral list.',
  },
  'tutors': {
    icon: 'Doc', angle: 'tutors',
    homeLine: 'Recurring sessions, prepaid packs, simple parent billing.',
    headline: 'Sessions, packages, and easy parent billing.',
    sub: 'Recurring sessions with auto-renewal, parent-pays-student-attends billing, and progress notes per subject.',
    bullets: [
      { title: 'Per-subject progress notes', body: 'Track Algebra II separately from SAT prep, even for the same student.' },
      { title: 'Simple parent billing', body: 'Bill the parent while the student attends - invoices, packs, and schedule on one client record.' },
      { title: 'Session packs', body: '10 hours of SAT prep up front. Auto-consumed per session.' },
      { title: 'Pause + resume', body: 'Summer break? Pause the recurrence; resume in fall with one click.' },
    ],
    use: 'Add subject-tagged services, save the parent’s contact + card, build a session pack.',
  },
  'music-teachers': {
    icon: 'Spark', angle: 'music teachers',
    homeLine: 'Weekly lessons, makeup credits, recital packets.',
    headline: 'Weekly lessons + makeup credits, automatically tracked.',
    sub: 'Recurring weekly lessons, auto-issued makeup credits, and recital event tracking in one calendar.',
    bullets: [
      { title: 'Makeup credits', body: 'Sell lesson packs with an expiry window; a cancellation frees the credit to rebook within the period.' },
      { title: 'Notes on every student', body: 'Keep practice notes and lesson history on each student’s record, ready before every lesson.' },
      { title: 'Recital tickets', body: 'Sell tickets to year-end recitals through your booking page.' },
      { title: 'Sheet music delivery', body: 'Attach PDF sheet music to a booking; it lives privately in the student’s portal.' },
    ],
    use: 'Add 30/45/60-min lesson services, set recurring weekly, configure makeup policy.',
  },
  'life-coaches': {
    icon: 'Spark', angle: 'life coaches',
    homeLine: 'Discovery calls, retainer agreements, weekly cadence.',
    headline: 'Discovery → retainer → outcome, in one cadence.',
    sub: 'Free discovery call, signed coaching agreement, weekly cadence, and outcome tracking - all in one continuous client record.',
    bullets: [
      { title: 'Discovery → onboard flow', body: 'Free 20-min call confirms; Ivy auto-sends the coaching agreement on conversion.' },
      { title: 'Recurring retainers', body: 'Monthly retainer auto-charges. Auto-book the standing weekly slot.' },
      { title: 'Notes & history', body: 'Keep private notes and a full session history on every client so progress is always in context.' },
      { title: 'Inter-session prompts', body: 'Auto-message between sessions with reflection prompts you design once.' },
    ],
    use: 'Add discovery call + coaching session services, build retainer package, upload your agreement.',
  },
  'career-coaches': {
    icon: 'Trending', angle: 'career coaches',
    homeLine: 'Resume reviews, interview prep, recurring strategy calls.',
    headline: 'Resume review → interview prep → offer, end to end.',
    sub: "Run a full-service career practice from one workspace: resume reviews, interview prep, salary negotiation, all with the same client record.",
    bullets: [
      { title: 'Document-review services', body: 'Async resume review service with file upload - bill flat-rate, deliver via signed document.' },
      { title: 'Live prep sessions', body: 'Schedule 1:1 mock interviews with calendar integration.' },
      { title: 'Salary-negotiation packages', body: 'Bundle 3 strategy calls + offer review - sold as a fixed package.' },
      { title: 'Reviews & testimonials', body: 'Auto-request a review after the engagement and showcase wins on your booking page.' },
    ],
    use: 'Add review + live coaching services, build the negotiation package, share your booking link.',
  },
  'consultants': {
    icon: 'Trending', angle: 'consultants',
    homeLine: 'Discovery → proposal → retainer → invoices, in one flow.',
    headline: 'The full consulting practice in one workspace.',
    sub: 'Discovery calls, signed proposals, recurring retainers, time tracking, expense logs, and tax-ready exports - all in one app.',
    bullets: [
      { title: 'Proposal generation', body: 'Build a templated proposal; client e-signs; Ivy creates the recurring invoice.' },
      { title: 'Retainer billing', body: 'Monthly retainer auto-charges. Optional time tracking surfaces unbilled hours.' },
      { title: 'Time + expenses', body: 'Track billable hours + reimbursable expenses. They flow onto the next invoice automatically.' },
      { title: 'Tax-ready exports', body: 'Schedule-C summary plus QuickBooks/Xero CSV exports, ready to hand your CPA.' },
    ],
    use: 'Add your discovery + project + retainer services. Build a proposal template. Configure Stripe.',
  },
  'therapists': {
    icon: 'Heart', angle: 'therapists & counselors',
    homeLine: 'Intake, progress notes, insurance-ready receipts, telehealth links.',
    headline: 'Cash-pay therapy practice, end to end.',
    sub: 'Intake forms, progress notes, insurance-ready receipts, telehealth links - every part of a private-pay therapy practice in one workspace.',
    bullets: [
      { title: 'Encrypted progress notes', body: 'Per-session SOAP-style notes that survive forever on the client record.' },
      { title: 'Telehealth link', body: 'Auto-generate a unique video link per session in confirmation emails.' },
      { title: 'Insurance-ready receipts', body: 'Itemized, branded invoices and receipts clients can submit for out-of-network reimbursement.' },
      { title: 'Flexible pricing', body: 'Price each service or send a custom-priced invoice for sliding-scale clients. Stripe handles the charge.' },
    ],
    use: 'Add your session types, build a SOAP-note template, set your receipt format.',
  },
  'nutritionists': {
    icon: 'Heart', angle: 'nutritionists & dietitians',
    homeLine: 'Intake, plan delivery, follow-ups, progress tracking.',
    headline: 'Intake, plans, follow-ups - auto-orchestrated.',
    sub: 'Initial consult, nutrition plan delivery, recurring check-ins, and progress tracking - all without juggling tools.',
    bullets: [
      { title: 'Per-client nutrition plans', body: 'Build the plan as a document; deliver via signed delivery; lives on the client record.' },
      { title: 'Automated check-ins', body: 'Workflows send weekly check-in messages by email or SMS; keep results in each client’s notes.' },
      { title: 'Recurring follow-ups', body: 'Book the next follow-up at the end of each session, or set a recurring series.' },
      { title: 'Group sessions', body: 'Run group classes with capacity alongside your 1:1 consults - all on one calendar.' },
    ],
    use: 'Add initial consult + follow-up services, build a plan template, set check-in cadence.',
  },
  'dog-walkers': {
    icon: 'Spark', angle: 'dog walkers & pet sitters',
    homeLine: 'Recurring walks, photo check-ins, easy billing.',
    headline: 'Recurring walks, transparency, easy billing.',
    sub: 'Recurring walks billed monthly, photo check-ins to the client portal, vet info on every pet record.',
    bullets: [
      { title: 'Pet records', body: 'Vet info, allergies, walk preferences - survive across every booking forever.' },
      { title: 'Photo check-ins', body: 'Snap a photo mid-walk and upload it to the client’s portal so owners stay in the loop.' },
      { title: 'Recurring billing', body: 'Monthly walk plan auto-charges. Late-cancel fees built in.' },
      { title: 'Key-pickup notes', body: 'Track lockbox codes per client, encrypted on their record.' },
    ],
    use: 'Add walk + sit services, build a monthly plan, share your booking link.',
  },
  'pet-groomers': {
    icon: 'Spark', angle: 'pet groomers',
    homeLine: 'Pet records, vaccination intake, recurring grooms.',
    headline: 'Pet records + recurring grooms, one workspace.',
    sub: 'Per-pet records with breed, temperament, last-groom notes - plus auto-recurring monthly grooms and vaccination intake.',
    bullets: [
      { title: 'Per-pet records', body: 'Breed, temperament, allergies, last-groom notes - all there next time.' },
      { title: 'Vaccination upload', body: 'Required intake on first booking; expiry alerts before renewal.' },
      { title: 'Recurring grooms', body: 'Monthly or 6-week cadence; auto-book the standing slot.' },
      { title: 'Breed-aware pricing', body: 'Per-breed price tier so you don\'t under-charge for doodles.' },
    ],
    use: 'Add groom services per size, set vaccination requirement, build a recurring slot.',
  },
  'real-estate-agents': {
    icon: 'Home', angle: 'real-estate agents',
    homeLine: 'Lead capture, showing scheduling, document signing.',
    headline: 'From lead to closing, one client record.',
    sub: 'Capture leads from your site, schedule showings, send disclosures for e-sign, run the deal end-to-end.',
    bullets: [
      { title: 'Lead capture forms', body: 'Embed inquiry forms on any site or landing page; new leads land in your CRM.' },
      { title: 'Showing scheduler', body: 'Set up bookable showing slots; prospects pick a time from your booking link.' },
      { title: 'Disclosure + offer signing', body: 'Multi-signer e-sign for every document in the file.' },
      { title: 'Lead pipeline', body: 'Track every contact by stage and tag - from new lead to active client - on one CRM.' },
    ],
    use: 'Add showing services, set your client stages + tags, upload your disclosure templates.',
  },
  'event-planners': {
    icon: 'Calendar', angle: 'event planners',
    homeLine: 'Discovery, contracts, vendor coordination, day-of timeline.',
    headline: 'From inquiry to day-of, one workspace.',
    sub: 'Capture inquiries, send contracts, manage vendors, coordinate timelines, bill milestones - all in one place.',
    bullets: [
      { title: 'Project-based pipeline', body: 'Each event is a project. All bookings + invoices + docs nested under it.' },
      { title: 'Tasks & checklists', body: 'Break each event into tasks with due dates so every deliverable has an owner and a deadline.' },
      { title: 'Stage payments', body: 'Deposit on contract, then balance invoices as you hit milestones - clients pay in a tap.' },
      { title: 'Everything on one record', body: 'Contracts, invoices, notes, and tasks for the event live together - the full picture in one tap.' },
    ],
    use: 'Build an event template, set milestone billing, upload your standard contract.',
  },
  'wedding-planners': {
    icon: 'Heart', angle: 'wedding planners',
    homeLine: 'Couples, vendors, contracts, day-of - orchestrated.',
    headline: 'Couples, vendors, and the day-of - all in sync.',
    sub: 'A full wedding-planning practice in one workspace. Inquiry forms, contracts, vendor team, milestone payments, and the day-of timeline.',
    bullets: [
      { title: 'Couple onboarding', body: 'Detailed questionnaire auto-sends on signed contract. No more "did you fill out the form?"' },
      { title: 'One project per wedding', body: 'Group every booking, invoice, document, and task for the wedding under a single project.' },
      { title: 'Stage payments', body: 'Deposit on signing, then milestone invoices as the date nears - clients pay in a tap.' },
      { title: 'Task timeline', body: 'Build the run-of-show as dated tasks and check them off as the day unfolds.' },
    ],
    use: 'Build a wedding project template, set milestone schedule, upload contract + questionnaire.',
  },
  'freelance-designers': {
    icon: 'Edit', angle: 'freelance designers',
    homeLine: 'Proposals, milestone invoices, async deliverables.',
    headline: 'A practice that scales without admin overhead.',
    sub: 'Send proposals, collect deposits, run async deliverables, bill milestones - all without 5 different SaaS tools.',
    bullets: [
      { title: 'Proposal templates', body: 'Re-usable proposals with scope + price + timeline. Client e-signs; you start the work.' },
      { title: 'Milestone invoicing', body: 'Bill in stages - sketch, revision, final - sending each invoice as you hit the milestone.' },
      { title: 'Async deliverables', body: 'Attach final files to the project and share them through the client’s portal.' },
      { title: 'Time + expense tracking', body: 'Track billable hours; auto-flow onto the next invoice.' },
    ],
    use: 'Add discovery + project + retainer services. Build a proposal template.',
  },
  'copywriters': {
    icon: 'Doc', angle: 'copywriters',
    homeLine: 'Retainers, project-based, brand-voice library.',
    headline: 'Retainers and project work, one workspace.',
    sub: 'Onboarding brief, brand-voice library per client, recurring retainers with delivery cadence, and invoicing on auto-pilot.',
    bullets: [
      { title: 'Brand-voice library', body: 'Per-client voice notes + sample copy. Surface them when you draft.' },
      { title: 'Recurring retainers', body: 'Monthly retainer = X pieces. Track delivery against the contracted scope.' },
      { title: 'Project-based work', body: 'Sales page, email sequence, white paper - bill flat-rate; deliver via signed file.' },
      { title: 'Async revisions', body: 'Client requests revisions inside the project record. No emails lost.' },
    ],
    use: 'Add retainer + project services, build voice templates, configure retainer schedule.',
  },
  'handymen': {
    icon: 'Edit', angle: 'handymen',
    homeLine: 'Quotes, deposits, on-site work, easy invoicing.',
    headline: 'From quote to invoice, in your pocket.',
    sub: 'Send quotes from the job site, take a deposit on the spot, invoice when you finish - all from your phone.',
    bullets: [
      { title: 'Mobile-first quoting', body: 'Snap photos at the site; send the quote in 2 minutes.' },
      { title: 'Deposit on confirm', body: 'Stripe takes the deposit when the client accepts. No chasing.' },
      { title: 'Job-site invoicing', body: 'Mark complete → invoice drafts itself with your standard line items.' },
      { title: 'Recurring jobs', body: '"Quarterly gutter clean" or "monthly pool service" - set the recurrence once.' },
    ],
    use: 'Add service categories, set deposit %, install the app on your phone.',
  },
};
