// Visual templates — each defines the base palette, typography, and radii
// that the rendered site will inherit. Templates are applied by scoping a
// CSS variable block on the outer wrapper.

export const TEMPLATES = {
  clean: {
    id: 'clean',
    name: 'Clean & Modern',
    desc: 'White space, minimal layout — lets your work speak.',
    vars: {
      '--site-bg':        '#FFFFFF',
      '--site-fg':        '#141414',
      '--site-fg-2':      '#4A4A46',
      '--site-muted':     '#85827B',
      '--site-accent':    '#2E3168',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#FAF8F3',
      '--site-border':    '#E8E4DC',
      '--site-radius':    '12px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
  warm: {
    id: 'warm',
    name: 'Warm & Personal',
    desc: 'Earthy tones, personal feel — great for coaches & wellness.',
    vars: {
      '--site-bg':        '#FBF7F0',
      '--site-fg':        '#2A1F14',
      '--site-fg-2':      '#5A4A3A',
      '--site-muted':     '#8C7560',
      '--site-accent':    '#B05F2C',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#F5EDDE',
      '--site-border':    '#E5DDCC',
      '--site-radius':    '16px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
  bold: {
    id: 'bold',
    name: 'Bold & Electric',
    desc: 'Dark background, bright accents — high-impact and memorable.',
    vars: {
      '--site-bg':        '#0D0E0C',
      '--site-fg':        '#F3F3EE',
      '--site-fg-2':      '#C9CAC3',
      '--site-muted':     '#8A8D85',
      '--site-accent':    '#CFFF50',
      '--site-accent-ink':'#0B0C08',
      '--site-surface':   '#1A1C1A',
      '--site-border':    '#262A2D',
      '--site-radius':    '10px',
      '--site-font-display': "'Space Grotesk', 'Inter', sans-serif",
      '--site-font-body':    "'Inter', sans-serif",
    },
  },
  studio: {
    id: 'studio',
    name: 'Studio',
    desc: 'Gallery-forward, image-heavy — photographers, designers, creatives.',
    vars: {
      '--site-bg':        '#F5F5F1',
      '--site-fg':        '#0F0F0F',
      '--site-fg-2':      '#3C3C39',
      '--site-muted':     '#6E6E6A',
      '--site-accent':    '#1A1A1A',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#FFFFFF',
      '--site-border':    '#E2E0DA',
      '--site-radius':    '4px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
  wellness: {
    id: 'wellness',
    name: 'Wellness',
    desc: 'Soft sage + cream, gentle pace — massage, yoga, body-work.',
    vars: {
      '--site-bg':        '#F4F1EA',
      '--site-fg':        '#1F2A23',
      '--site-fg-2':      '#4B5A50',
      '--site-muted':     '#8A9789',
      '--site-accent':    '#5B7C5F',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#EAE6DB',
      '--site-border':    '#D5CFC0',
      '--site-radius':    '20px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
  editorial: {
    id: 'editorial',
    name: 'Editorial',
    desc: 'Magazine-style — heavy serif headlines, generous whitespace, writers + thinkers.',
    vars: {
      '--site-bg':        '#FAF8F4',
      '--site-fg':        '#0A0A0A',
      '--site-fg-2':      '#2E2E2E',
      '--site-muted':     '#7A7872',
      '--site-accent':    '#8B0E1F',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#F1EDE3',
      '--site-border':    '#DAD5C9',
      '--site-radius':    '2px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Fraunces', Georgia, serif",
    },
  },
  mono: {
    id: 'mono',
    name: 'Mono',
    desc: 'Black, white, one accent — minimalist for consultants + lawyers.',
    vars: {
      '--site-bg':        '#FFFFFF',
      '--site-fg':        '#000000',
      '--site-fg-2':      '#2C2C2C',
      '--site-muted':     '#7B7B7B',
      '--site-accent':    '#000000',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#F4F4F4',
      '--site-border':    '#1A1A1A',
      '--site-radius':    '0px',
      '--site-font-display': "'Space Grotesk', 'Inter', sans-serif",
      '--site-font-body':    "'Inter', sans-serif",
    },
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    desc: 'Warm peach + coral — lifestyle, coaching, hospitality.',
    vars: {
      '--site-bg':        '#FFF4EC',
      '--site-fg':        '#2A1814',
      '--site-fg-2':      '#5B342C',
      '--site-muted':     '#9C7264',
      '--site-accent':    '#E5572B',
      '--site-accent-ink':'#FFFFFF',
      '--site-surface':   '#FCE4D2',
      '--site-border':    '#F2D2BC',
      '--site-radius':    '14px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    desc: 'Deep green + bone — outdoorsy, organic, premium.',
    vars: {
      '--site-bg':        '#15201A',
      '--site-fg':        '#F1ECE0',
      '--site-fg-2':      '#C8C0A8',
      '--site-muted':     '#8C8773',
      '--site-accent':    '#D4B470',
      '--site-accent-ink':'#1A2620',
      '--site-surface':   '#1F2B23',
      '--site-border':    '#2B3A30',
      '--site-radius':    '8px',
      '--site-font-display': "'Fraunces', Georgia, serif",
      '--site-font-body':    "'Inter', -apple-system, sans-serif",
    },
  },
};

export const TEMPLATE_LIST = Object.values(TEMPLATES);
